# Generated by Django 4.0.5 on 2022-07-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='apellido',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='familiares',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='familiares',
            name='parentesco',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='fechaDeNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='hijos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
