# Generated by Django 4.0.5 on 2022-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_alter_familiares_fechadenacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='fechaDeNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
